# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin_interact.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Administrator(object):
    def setupUi(self, Administrator):
        Administrator.setObjectName("Administrator")
        Administrator.resize(400, 300)
        self.pushButton = QtWidgets.QPushButton(Administrator)
        self.pushButton.setGeometry(QtCore.QRect(120, 90, 131, 40))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Administrator)
        self.label.setGeometry(QtCore.QRect(80, 50, 281, 20))
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(Administrator)
        self.pushButton_2.setGeometry(QtCore.QRect(120, 140, 131, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Administrator)
        self.pushButton_3.setGeometry(QtCore.QRect(120, 190, 131, 40))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Administrator)
        self.pushButton_4.setGeometry(QtCore.QRect(120, 240, 131, 40))
        self.pushButton_4.setObjectName("pushButton_4")

        self.retranslateUi(Administrator)
        self.pushButton.clicked.connect(Administrator.click_add_book) # type: ignore
        self.pushButton_2.clicked.connect(Administrator.click_add_card) # type: ignore
        self.pushButton_3.clicked.connect(Administrator.click_delete_book) # type: ignore
        self.pushButton_4.clicked.connect(Administrator.click_delete_card) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Administrator)

    def retranslateUi(self, Administrator):
        _translate = QtCore.QCoreApplication.translate
        Administrator.setWindowTitle(_translate("Administrator", "管理员"))
        self.pushButton.setText(_translate("Administrator", "添加新书"))
        self.label.setText(_translate("Administrator", "请问您要进行的操作是："))
        self.pushButton_2.setText(_translate("Administrator", "添加新卡"))
        self.pushButton_3.setText(_translate("Administrator", "删除书籍"))
        self.pushButton_4.setText(_translate("Administrator", "删除借书证"))
