# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sign_in.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QLineEdit


class Ui_signin(object):
    def setupUi(self, signin):
        signin.setObjectName("signin")
        signin.resize(400, 300)
        self.label = QtWidgets.QLabel(signin)
        self.label.setGeometry(QtCore.QRect(70, 50, 271, 21))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(signin)
        self.pushButton.setGeometry(QtCore.QRect(140, 200, 91, 41))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(signin)
        self.label_2.setGeometry(QtCore.QRect(60, 90, 61, 21))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(signin)
        self.lineEdit.setGeometry(QtCore.QRect(120, 90, 151, 28))
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(signin)
        self.label_3.setGeometry(QtCore.QRect(60, 140, 61, 21))
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(signin)
        self.lineEdit_2.setGeometry(QtCore.QRect(120, 140, 151, 28))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.setEchoMode(QLineEdit.Password)

        self.retranslateUi(signin)
        self.pushButton.clicked.connect(signin.comfirm) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(signin)

    def retranslateUi(self, signin):
        _translate = QtCore.QCoreApplication.translate
        signin.setWindowTitle(_translate("signin", "登陆"))
        self.label.setText(_translate("signin", "请输入您的账号和密码："))
        self.pushButton.setText(_translate("signin", "确定"))
        self.label_2.setText(_translate("signin", "账号："))
        self.label_3.setText(_translate("signin", "密码："))
